repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5
  hooks:
  - id: autopep8
    args:
      - --in-place
      - --aggressive
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
- repo: git://github.com/doublify/pre-commit-isort
  rev: v4.3.0
  hooks:
  - id: isort
