language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
install:
  - pip install tox
  - cp local_settings.cfg.example local_settings.cfg
script:
  - tox
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=linting
notifications:
  email: false
