language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
install:
  - pip install -r requirements.txt
  - pip install pre-commit && pre-commit install
script:
  - pre-commit run --all-files --show-diff-on-failure
notifications:
  email: false
