[tox]
envlist = py312, linting
skipsdist = True

[testenv]
skip_install = True

[testenv:py312]
allowlist_externals = docker
passenv =
  USER
commands =
  docker build -t as_export_test --target test .
  docker run \
    --env AWS_ACCESS_KEY_ID=12345 \
    --env AWS_SECRET_ACCESS_KEY=987654321 \
    --env AWS_S3_ROLE=arn:aws:iam::123456789:role/s3_role \
    --env AWS_SSM_ROLE=arn:aws:iam::123456789:role/ssm_role \
    --env ENVIRONMENT=dev \
    as_export_test sh -c "coverage run -m pytest -s && coverage report -m" \

[testenv:linting]
allowlist_externals = pre-commit
basepython = python3
deps = pre-commit
commands =
    pre-commit run --all-files

[flake8]
application-import-names = flake8
select = B, C, E, F, W, B950
import-order-style = pep8
max-complexity = 10
max-line-length = 160
ignore =
  # Line too long (82 > 79 characters).
	E501,
  # Blank line at end of file
	W391,