[tox]
envlist = py311, linting
skipsdist = True

[testenv]
skip_install = True

[testenv:py311]
allowlist_externals = docker
passenv =
  USER
commands =
  docker build -t digital_ingest_discovery_test --target test .
  docker run digital_ingest_discovery_test bash -c "coverage run -m pytest -s && coverage report -m"

[testenv:linting]
allowlist_externals = pre-commit
basepython = python3
deps = pre-commit
commands =
    pre-commit run --all-files

[flake8]
application-import-names = flake8
select = B, C, E, F, W, B950
import-order-style = pep8
max-complexity = 10
max-line-length = 160
ignore =
  # Line too long (82 > 79 characters).
	E501,
  # Blank line at end of file
	W391,